<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-M8LMA397" ignored="0" name="RestAssuredtest" tests="8" failures="2" timestamp="2019-11-04T00:19:30 CST" time="2.916" errors="0">
  <testcase name="checkresponsetime" time="0.007" classname="testCases.TC1_Get_AllEmployee">
    <failure type="java.lang.AssertionError" message="expected [100] but found [1370]">
      <![CDATA[java.lang.AssertionError: expected [100] but found [1370]
at testCases.TC1_Get_AllEmployee.checkresponsetime(TC1_Get_AllEmployee.java:71)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkresponsetime -->
  <testcase name="checkstatusbody" time="0.099" classname="testCases.TC1_Get_AllEmployee"/>
  <testcase name="checkstatuscode" time="0.003" classname="testCases.TC1_Get_AllEmployee"/>
  <testcase name="checkstatusline" time="0.003" classname="testCases.TC1_Get_AllEmployee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [HTTP/1.1 200 OK]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [HTTP/1.1 200 OK]
at testCases.TC1_Get_AllEmployee.checkstatusline(TC1_Get_AllEmployee.java:47)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusline -->
  <testcase name="checkresponsetime" time="0.004" classname="testCases.TC2_Post_Employee"/>
  <testcase name="checkstatusbody" time="0.051" classname="testCases.TC2_Post_Employee"/>
  <testcase name="checkstatuscode" time="0.007" classname="testCases.TC2_Post_Employee"/>
  <testcase name="checkstatusline" time="0.005" classname="testCases.TC2_Post_Employee"/>
</testsuite> <!-- RestAssuredtest -->
